<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', TextType::class, [
                'label'=> 'Votre prénom'
            ])
            ->add('lastname', TextType::class, [
                'label'=> 'Votre nom'
            ])
            ->add('phone', TelType::class, [
                'label'=> 'Votre numéro de telephone (facultatif)',
                'required'=>false
            ])
            ->add('email', EmailType::class, [
                'label'=> 'Votre email'
            ])
            ->add('message', TextareaType::class, [
                'label'=> 'Votre message'
            ])
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}
